const recipesData = [
    {
        id: 1,
        categories: [],
        name: "",
        description: "",
        type: "",
        time: "",
        difficulty: "",
        ingredients: [],
        steps: [],
        photo: "",
    },
    {
        id: 2,
        categories: [],
        name: "",
        description: "",
        type: "",
        time: "",
        difficulty: "",
        ingredients: [],
        steps: [],
        photo: "",
    },
    {
        id: 3,
        categories: [],
        name: "",
        description: "",
        type: "",
        time: "",
        difficulty: "",
        ingredients: [],
        steps: [],
        photo: "",
    },
    {
        id: 4,
        categories: [],
        name: "",
        description: "",
        type: "",
        time: "",
        difficulty: "",
        ingredients: [],
        steps: [],
        photo: "",
    },
    {
        id: 5,
        categories: [],
        name: "",
        description: "",
        type: "",
        time: "",
        difficulty: "",
        ingredients: [],
        steps: [],
        photo: "",
    },
    {
        id: 6,
        categories: [],
        name: "",
        description: "",
        type: "",
        time: "",
        difficulty: "",
        ingredients: [],
        steps: [],
        photo: "",
    },
    {
        id: 7,
        categories: [],
        name: "",
        description: "",
        type: "",
        time: "",
        difficulty: "",
        ingredients: [],
        steps: [],
        photo: "",
    },
    {
        id: 8,
        categories: [],
        name: "",
        description: "",
        type: "",
        time: "",
        difficulty: "",
        ingredients: [],
        steps: [],
        photo: "",
    },
    {
        id: 9,
        categories: [],
        name: "",
        description: "",
        type: "",
        time: "",
        difficulty: "",
        ingredients: [],
        steps: [],
        photo: "",
    },
    {
        id: 10,
        categories: [],
        name: "",
        description: "",
        type: "",
        time: "",
        difficulty: "",
        ingredients: [],
        steps: [],
        photo: "",
    },
    {
        id: 11,
        categories: [],
        name: "",
        description: "",
        type: "",
        time: "",
        difficulty: "",
        ingredients: [],
        steps: [],
        photo: "",
    }
]